---
name: flake8

on:
  push:
    paths:
      - "**.py"
      - ".flake8"
      - "requirements.txt"
      - ".github/workflows/flake8.yaml"
      - ".github/workflows/.python-version"
  pull_request:
    paths:
      - "**.py"
      - ".flake8"
      - "requirements.txt"
      - ".github/workflows/flake8.yaml"
      - ".github/workflows/.python-version"

jobs:
  flake8:
    name: Python Lint Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.github/workflows/.python-version'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 --show-source --statistics .
