---
name: isort

on:
  push:
    paths:
      - "**.py"
      - ".isort.cfg"
      - "requirements.txt"
      - ".github/workflows/isort.yaml"
      - ".github/workflows/.python-version"
  pull_request:
    paths:
      - "**.py"
      - ".isort.cfg"
      - "requirements.txt"
      - ".github/workflows/isort.yaml"
      - ".github/workflows/.python-version"

jobs:
  isort:
    name: runner / isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v6
        with:
          python-version-file: '.github/workflows/.python-version'

      - name: Install isort
        run: pip install isort

      # - name: Install requirements
      #   run: pip install -r requirements.txt

      - name: Run isort
        run: isort . --check --diff
