---
name: prefetch_from_url

on:
  workflow_dispatch:
    inputs:
      url_to_prefetch:
        description: "URL to turn into a prefetch"
        default: https://download-installer.cdn.mozilla.net/pub/firefox/releases/151.0.3/mac/en-US/Firefox%20151.0.3.dmg
        required: true
        type: string
  push:
    paths:
      - ".github/workflows/prefetch_from_url.yaml"


env:
  url_to_prefetch: https://download-installer.cdn.mozilla.net/pub/firefox/releases/151.0.3/mac/en-US/Firefox%20151.0.3.dmg


jobs:
  prefetch_from_url:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install bigfix-prefetch
        run: pip install bigfix-prefetch

      - name: setup output
        run: |
          echo "# Prefetch From URL" >> $GITHUB_STEP_SUMMARY
          echo "## Input URL:" >> $GITHUB_STEP_SUMMARY
          echo "\`" >> $GITHUB_STEP_SUMMARY
          echo '${{ inputs.url_to_prefetch || env.url_to_prefetch }}' >> $GITHUB_STEP_SUMMARY
          echo "\`" >> $GITHUB_STEP_SUMMARY
          echo "## Prefech Statement:" >> $GITHUB_STEP_SUMMARY


      - name: run bigfix-prefetch
        run: |
          echo "\`" > output.md
          python -m bigfix_prefetch ${{ inputs.url_to_prefetch || env.url_to_prefetch }} > prefetch-output.txt
          cat prefetch-output.txt >> output.md
          echo "\`" >> output.md
          cat output.md
          cat output.md >> $GITHUB_STEP_SUMMARY
