---
name: pylint

on:
  push:
    paths:
      - "**.py"
      - ".pylintrc"
      - "requirements.txt"
      - ".github/workflows/pylint.yaml"
      - ".github/workflows/.python-version"
  pull_request:
    paths:
      - "**.py"
      - ".pylintrc"
      - "requirements.txt"
      - ".github/workflows/pylint.yaml"
      - ".github/workflows/.python-version"

jobs:
  pylint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: '.github/workflows/.python-version'

      - name: Install pylint
        run: pip install pylint setuptools

      - name: pylint files
        # https://stackoverflow.com/a/63044665/861745
        run: pylint $(git ls-files '*.py')
