---
name: YAML Lint

on:
  push:
    paths:
      - "**.yaml"
      - "**.yml"
      - ".github/workflows/.python-version"
  pull_request:
    paths:
      - "**.yaml"
      - "**.yml"
      - ".github/workflows/.python-version"

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.github/workflows/.python-version'

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint . -f parsable
